env:
  browser: true
  es2021: true
extends: ["airbnb-base", "plugin:prettier/recommended"]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: "off"
  no-await-in-loop:
    - warn
  radix:
    - error
    - as-needed
  default-param-last:
    - warn
  no-underscore-dangle: "off"
  no-param-reassign:
    - warn
  class-methods-use-this:
    - warn
  no-unused-vars:
    - warn
  no-nested-ternary: "off"
  no-restricted-syntax:
    - warn
    - selector: ForInStatement
      message:
        for..in loops iterate over the entire prototype chain, which is virtually
        never what you want. Use Object.{keys,values,entries}, and iterate over the
        resulting array.
    - selector: LabeledStatement
      message:
        Labels are a form of GOTO; using them makes code confusing and hard to
        maintain and understand.
    - selector: WithStatement
      message:
        "`with` is disallowed in strict mode because it makes code impossible
        to predict and optimize."
  import/extensions:
    - warn
    - always
globals:
  "$": readonly
  ActiveEffect: readonly
  ActiveEffectConfig: readonly
  Actor: readonly
  Actors: readonly
  ActorSheet: readonly
  Babele: readonly
  CONFIG: readonly
  CONST: readonly
  ChatMessage: readonly
  Combat: readonly
  Combatant: readonly
  ContextMenu: readonly
  Dialog: readonly
  DocumentSheetConfig: readonly
  Folder: readonly
  FormApplication: readonly
  FormDataExtended: readonly
  Handlebars: readonly
  Hooks: readonly
  ImagePopout: readonly
  Item: readonly
  Items: readonly
  ItemSheet: readonly
  Macro: readonly
  Roll: readonly
  Ruler: readonly
  Scene: readonly
  TextEditor: readonly
  TokenDocument: readonly
  canvas: readonly
  debugger: readonly
  document: readonly
  dragRuler: readonly
  duplicate: readonly
  foundry: readonly
  fromUuid: readonly
  fromUuidSync: readonly
  game: readonly
  getProperty: readonly
  globals: readonly
  hasProperty: readonly
  isNewerVersion: readonly
  loadTemplates: readonly
  mergeObject: readonly
  parseUuid: readonly
  randomID: readonly
  renderTemplate: readonly
  setProperty: readonly
  ui: readonly
  window: readonly
settings:
  import/extensions:
    - ".js"
